import type { DisclosureStandardItem } from "@/types/esg";

export const DISCLOSURE_STANDARD_ITEMS: DisclosureStandardItem[] = [
  {
    id: "gri-201-economic-performance",
    standardId: "gri-lite",
    code: "GRI 201",
    title: "Economic Performance",
    category: "G",
    theme: "经济绩效",
    requirementSummary: "披露经济绩效、价值创造与分配，以及可持续发展事项对经营和财务表现的影响。",
    requiredEvidenceTypes: ["财务/业务数据", "公司概况"],
    suggestedMetrics: ["营业收入", "经济价值分配", "重大可持续发展相关财务影响"],
    suggestedDepartments: ["财务部", "战略发展部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "gri-205-anti-corruption",
    standardId: "gri-lite",
    code: "GRI 205",
    title: "Anti-corruption",
    category: "G",
    theme: "商业道德",
    requirementSummary: "披露反腐败风险识别、培训、沟通和已确认事件的处理机制。",
    requiredEvidenceTypes: ["合规与风控", "供应链管理"],
    suggestedMetrics: ["反腐败培训覆盖率", "廉洁承诺签署率", "已确认腐败事件数量"],
    suggestedDepartments: ["法务合规部", "审计监察部"],
    riskLevelIfMissing: "高",
  },
  {
    id: "gri-302-energy",
    standardId: "gri-lite",
    code: "GRI 302",
    title: "Energy",
    category: "E",
    theme: "能源管理",
    requirementSummary: "披露组织内外能源消耗、能源强度和节能改善措施。",
    requiredEvidenceTypes: ["环境数据", "财务/业务数据"],
    suggestedMetrics: ["综合能耗", "外购电力使用量", "能源强度", "节能项目数量"],
    suggestedDepartments: ["生产运营部", "行政后勤部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "gri-303-water-effluents",
    standardId: "gri-lite",
    code: "GRI 303",
    title: "Water and Effluents",
    category: "E",
    theme: "水资源",
    requirementSummary: "披露取水、用水、排水及水资源压力相关管理措施。",
    requiredEvidenceTypes: ["环境数据", "合规与风控"],
    suggestedMetrics: ["取水量", "用水量", "循环用水量", "废水排放量"],
    suggestedDepartments: ["环境管理部", "生产运营部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "gri-304-biodiversity",
    standardId: "gri-lite",
    code: "GRI 304",
    title: "Biodiversity",
    category: "E",
    theme: "生物多样性",
    requirementSummary: "披露业务地点对生态系统和生物多样性的潜在影响及保护措施。",
    requiredEvidenceTypes: ["环境数据", "合规与风控"],
    suggestedMetrics: ["保护区相关经营点数量", "生态修复投入", "受影响栖息地面积"],
    suggestedDepartments: ["环境管理部", "项目建设部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "gri-305-emissions",
    standardId: "gri-lite",
    code: "GRI 305",
    title: "Emissions",
    category: "E",
    theme: "温室气体与排放",
    requirementSummary: "披露范围一、范围二及相关范围三温室气体排放、排放强度和减排措施。",
    requiredEvidenceTypes: ["环境数据", "财务/业务数据"],
    suggestedMetrics: ["范围一排放", "范围二排放", "范围三排放", "排放强度"],
    suggestedDepartments: ["ESG办公室", "环境管理部"],
    riskLevelIfMissing: "高",
  },
  {
    id: "gri-306-waste",
    standardId: "gri-lite",
    code: "GRI 306",
    title: "Waste",
    category: "E",
    theme: "废弃物",
    requirementSummary: "披露废弃物产生、回收、转移、处置和减量化管理情况。",
    requiredEvidenceTypes: ["环境数据", "合规与风控"],
    suggestedMetrics: ["一般废弃物产生量", "危险废弃物产生量", "回收利用量", "合规处置率"],
    suggestedDepartments: ["环境管理部", "安全生产部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "gri-401-employment",
    standardId: "gri-lite",
    code: "GRI 401",
    title: "Employment",
    category: "S",
    theme: "员工雇佣",
    requirementSummary: "披露员工雇佣、离职、福利和员工权益保障情况。",
    requiredEvidenceTypes: ["员工与社会责任"],
    suggestedMetrics: ["员工总数", "新进员工人数", "员工流失率", "福利覆盖率"],
    suggestedDepartments: ["人力资源部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "gri-403-occupational-health-safety",
    standardId: "gri-lite",
    code: "GRI 403",
    title: "Occupational Health and Safety",
    category: "S",
    theme: "职业健康与安全",
    requirementSummary: "披露职业健康安全管理体系、培训、事故统计和隐患整改。",
    requiredEvidenceTypes: ["员工与社会责任", "合规与风控"],
    suggestedMetrics: ["工伤事故数", "损失工时事故率", "安全培训覆盖率", "隐患整改完成率"],
    suggestedDepartments: ["安全生产部", "人力资源部"],
    riskLevelIfMissing: "高",
  },
  {
    id: "gri-404-training-education",
    standardId: "gri-lite",
    code: "GRI 404",
    title: "Training and Education",
    category: "S",
    theme: "培训与发展",
    requirementSummary: "披露员工培训体系、平均培训时长、能力提升和职业发展机制。",
    requiredEvidenceTypes: ["员工与社会责任"],
    suggestedMetrics: ["人均培训小时数", "培训覆盖率", "关键岗位培养人数"],
    suggestedDepartments: ["人力资源部", "培训发展部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "gri-405-diversity-equal-opportunity",
    standardId: "gri-lite",
    code: "GRI 405",
    title: "Diversity and Equal Opportunity",
    category: "S",
    theme: "多元化与平等机会",
    requirementSummary: "披露治理层和员工队伍的多元化构成及平等机会管理。",
    requiredEvidenceTypes: ["员工与社会责任", "公司治理"],
    suggestedMetrics: ["女性员工比例", "管理层女性比例", "少数群体员工比例"],
    suggestedDepartments: ["人力资源部", "董事会办公室"],
    riskLevelIfMissing: "中",
  },
  {
    id: "gri-414-supplier-social-assessment",
    standardId: "gri-lite",
    code: "GRI 414",
    title: "Supplier Social Assessment",
    category: "S",
    theme: "供应链社会评估",
    requirementSummary: "披露供应商社会责任评估、准入、整改和负面影响管理。",
    requiredEvidenceTypes: ["供应链管理", "合规与风控"],
    suggestedMetrics: ["接受社会责任评估的供应商比例", "整改完成率", "高风险供应商数量"],
    suggestedDepartments: ["采购部", "供应链管理部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "gri-418-customer-privacy",
    standardId: "gri-lite",
    code: "GRI 418",
    title: "Customer Privacy",
    category: "G",
    theme: "客户隐私",
    requirementSummary: "披露客户隐私保护制度、投诉处理和数据泄露事件应对。",
    requiredEvidenceTypes: ["合规与风控", "财务/业务数据"],
    suggestedMetrics: ["隐私投诉数量", "数据泄露事件数量", "隐私培训覆盖率"],
    suggestedDepartments: ["信息技术部", "法务合规部"],
    riskLevelIfMissing: "高",
  },
  {
    id: "cn-climate-change",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-01",
    title: "应对气候变化",
    category: "E",
    theme: "气候变化",
    requirementSummary: "披露气候相关治理、风险机遇、减排目标和低碳转型措施。",
    requiredEvidenceTypes: ["环境数据", "合规与风控"],
    suggestedMetrics: ["温室气体排放量", "减排目标完成率", "低碳项目投入"],
    suggestedDepartments: ["ESG办公室", "环境管理部"],
    riskLevelIfMissing: "高",
  },
  {
    id: "cn-pollution-emissions",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-02",
    title: "污染物排放",
    category: "E",
    theme: "污染物管理",
    requirementSummary: "披露主要污染物排放、排污许可、达标监测和减排治理措施。",
    requiredEvidenceTypes: ["环境数据", "合规与风控"],
    suggestedMetrics: ["主要污染物排放量", "排放达标率", "环保处罚次数"],
    suggestedDepartments: ["环境管理部", "法务合规部"],
    riskLevelIfMissing: "高",
  },
  {
    id: "cn-waste-treatment",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-03",
    title: "废弃物处理",
    category: "E",
    theme: "废弃物",
    requirementSummary: "披露一般废弃物和危险废弃物的产生、分类、转移和合规处置情况。",
    requiredEvidenceTypes: ["环境数据", "合规与风控"],
    suggestedMetrics: ["一般废弃物产生量", "危险废弃物产生量", "合规处置率"],
    suggestedDepartments: ["环境管理部", "安全生产部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "cn-biodiversity",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-04",
    title: "生态系统和生物多样性保护",
    category: "E",
    theme: "生物多样性",
    requirementSummary: "披露生产经营对生态系统的影响识别、保护措施和生态修复实践。",
    requiredEvidenceTypes: ["环境数据", "合规与风控"],
    suggestedMetrics: ["生态保护投入", "修复面积", "生态风险评估覆盖率"],
    suggestedDepartments: ["环境管理部", "项目建设部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "cn-environmental-compliance",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-05",
    title: "环境合规管理",
    category: "E",
    theme: "环境合规",
    requirementSummary: "披露环境管理制度、许可资质、处罚整改和环境风险应急机制。",
    requiredEvidenceTypes: ["环境数据", "合规与风控"],
    suggestedMetrics: ["环保处罚次数", "整改完成率", "环境应急演练次数"],
    suggestedDepartments: ["环境管理部", "法务合规部"],
    riskLevelIfMissing: "高",
  },
  {
    id: "cn-energy-use",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-06",
    title: "能源利用",
    category: "E",
    theme: "能源管理",
    requirementSummary: "披露能源使用结构、能源消耗强度、节能措施和可再生能源使用情况。",
    requiredEvidenceTypes: ["环境数据", "财务/业务数据"],
    suggestedMetrics: ["综合能耗", "单位产值能耗", "可再生能源占比"],
    suggestedDepartments: ["生产运营部", "行政后勤部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "cn-water-use",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-07",
    title: "水资源利用",
    category: "E",
    theme: "水资源",
    requirementSummary: "披露取水、用水、节水、循环水利用和水资源风险管理。",
    requiredEvidenceTypes: ["环境数据", "合规与风控"],
    suggestedMetrics: ["取水量", "单位产值耗水量", "循环用水率"],
    suggestedDepartments: ["环境管理部", "生产运营部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "cn-circular-economy",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-08",
    title: "循环经济",
    category: "E",
    theme: "资源循环",
    requirementSummary: "披露资源综合利用、再生材料使用、包装减量和循环利用项目。",
    requiredEvidenceTypes: ["环境数据", "财务/业务数据"],
    suggestedMetrics: ["资源回收利用量", "再生材料占比", "循环经济项目投入"],
    suggestedDepartments: ["生产运营部", "环境管理部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "cn-rural-revitalization",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-09",
    title: "乡村振兴",
    category: "S",
    theme: "社会贡献",
    requirementSummary: "披露乡村振兴项目、投入资源、帮扶成效和长期机制。",
    requiredEvidenceTypes: ["员工与社会责任", "财务/业务数据"],
    suggestedMetrics: ["乡村振兴投入金额", "帮扶项目数量", "受益人数"],
    suggestedDepartments: ["品牌公关部", "行政部"],
    riskLevelIfMissing: "低",
  },
  {
    id: "cn-social-contribution",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-10",
    title: "社会贡献",
    category: "S",
    theme: "社会贡献",
    requirementSummary: "披露公益慈善、志愿服务、社区沟通和社会价值创造情况。",
    requiredEvidenceTypes: ["员工与社会责任", "财务/业务数据"],
    suggestedMetrics: ["公益投入金额", "志愿服务小时数", "社区项目数量"],
    suggestedDepartments: ["品牌公关部", "行政部"],
    riskLevelIfMissing: "低",
  },
  {
    id: "cn-innovation-driven",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-11",
    title: "创新驱动",
    category: "S",
    theme: "创新发展",
    requirementSummary: "披露研发投入、创新成果、知识产权和创新能力建设。",
    requiredEvidenceTypes: ["财务/业务数据", "公司概况"],
    suggestedMetrics: ["研发投入金额", "研发人员数量", "专利数量"],
    suggestedDepartments: ["研发部", "战略发展部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "cn-tech-ethics",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-12",
    title: "科技伦理",
    category: "G",
    theme: "科技治理",
    requirementSummary: "披露新技术研发和应用中的伦理审查、风险评估和治理机制。",
    requiredEvidenceTypes: ["合规与风控", "公司治理"],
    suggestedMetrics: ["伦理审查项目数量", "科技伦理培训覆盖率", "高风险技术评估次数"],
    suggestedDepartments: ["研发部", "法务合规部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "cn-supply-chain-security",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-13",
    title: "供应链安全",
    category: "S",
    theme: "供应链管理",
    requirementSummary: "披露供应链韧性、供应商准入、风险评估和应急保障机制。",
    requiredEvidenceTypes: ["供应链管理", "合规与风控"],
    suggestedMetrics: ["关键供应商数量", "供应商评估覆盖率", "供应中断事件数量"],
    suggestedDepartments: ["采购部", "供应链管理部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "cn-sme-fair-treatment",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-14",
    title: "平等对待中小企业",
    category: "G",
    theme: "公平交易",
    requirementSummary: "披露供应链合作中对中小企业的公平准入、账期管理和权益保障。",
    requiredEvidenceTypes: ["供应链管理", "财务/业务数据"],
    suggestedMetrics: ["中小企业供应商占比", "平均付款账期", "逾期付款金额"],
    suggestedDepartments: ["采购部", "财务部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "cn-product-service-safety-quality",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-15",
    title: "产品和服务安全与质量",
    category: "S",
    theme: "产品责任",
    requirementSummary: "披露产品和服务质量、安全管理、客户投诉和改进机制。",
    requiredEvidenceTypes: ["财务/业务数据", "合规与风控"],
    suggestedMetrics: ["产品质量合格率", "客户投诉数量", "召回事件数量"],
    suggestedDepartments: ["品质管理部", "客户服务部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "cn-data-security-customer-privacy",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-16",
    title: "数据安全与客户隐私保护",
    category: "G",
    theme: "数据安全",
    requirementSummary: "披露数据安全、网络安全、个人信息保护和客户隐私事件应对机制。",
    requiredEvidenceTypes: ["合规与风控", "财务/业务数据"],
    suggestedMetrics: ["数据安全事件数量", "隐私投诉数量", "安全培训覆盖率"],
    suggestedDepartments: ["信息技术部", "法务合规部"],
    riskLevelIfMissing: "高",
  },
  {
    id: "cn-employee-rights",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-17",
    title: "员工权益",
    category: "S",
    theme: "员工权益",
    requirementSummary: "披露雇佣合规、薪酬福利、平等机会、员工沟通和权益保障。",
    requiredEvidenceTypes: ["员工与社会责任"],
    suggestedMetrics: ["员工总数", "劳动合同签订率", "员工流失率", "员工沟通次数"],
    suggestedDepartments: ["人力资源部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "cn-occupational-health-safety",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-18",
    title: "职业健康与安全",
    category: "S",
    theme: "职业健康与安全",
    requirementSummary: "披露安全生产、职业健康管理、培训、事故和隐患整改情况。",
    requiredEvidenceTypes: ["员工与社会责任", "合规与风控"],
    suggestedMetrics: ["安全培训覆盖率", "工伤事故数量", "隐患整改完成率"],
    suggestedDepartments: ["安全生产部", "人力资源部"],
    riskLevelIfMissing: "高",
  },
  {
    id: "cn-due-diligence",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-19",
    title: "尽职调查",
    category: "G",
    theme: "尽职调查",
    requirementSummary: "披露对重大 ESG 风险、供应链和业务伙伴的尽职调查流程与结果应用。",
    requiredEvidenceTypes: ["合规与风控", "供应链管理"],
    suggestedMetrics: ["尽职调查覆盖率", "高风险事项数量", "整改完成率"],
    suggestedDepartments: ["法务合规部", "供应链管理部"],
    riskLevelIfMissing: "高",
  },
  {
    id: "cn-stakeholder-communication",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-20",
    title: "利益相关方沟通",
    category: "G",
    theme: "利益相关方",
    requirementSummary: "披露识别利益相关方、沟通渠道、关注议题和反馈响应机制。",
    requiredEvidenceTypes: ["公司治理", "员工与社会责任"],
    suggestedMetrics: ["利益相关方沟通次数", "重大议题数量", "反馈关闭率"],
    suggestedDepartments: ["ESG办公室", "董事会办公室"],
    riskLevelIfMissing: "中",
  },
  {
    id: "cn-anti-bribery-corruption",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-21",
    title: "反商业贿赂及反贪污",
    category: "G",
    theme: "商业道德",
    requirementSummary: "披露反商业贿赂和反贪污制度、培训、举报与调查处理情况。",
    requiredEvidenceTypes: ["合规与风控", "供应链管理"],
    suggestedMetrics: ["廉洁培训覆盖率", "举报案件数量", "供应商廉洁承诺签署率"],
    suggestedDepartments: ["法务合规部", "审计监察部"],
    riskLevelIfMissing: "高",
  },
  {
    id: "cn-anti-unfair-competition",
    standardId: "cn-exchange-lite",
    code: "CN-Lite-22",
    title: "反不正当竞争",
    category: "G",
    theme: "公平竞争",
    requirementSummary: "披露公平竞争、反垄断、商业秘密保护和合规营销管理机制。",
    requiredEvidenceTypes: ["合规与风控", "财务/业务数据"],
    suggestedMetrics: ["公平竞争培训覆盖率", "相关投诉或处罚次数", "合规审查次数"],
    suggestedDepartments: ["法务合规部", "市场部"],
    riskLevelIfMissing: "高",
  },
  {
    id: "issb-ifrs-s1-general",
    standardId: "issb-lite",
    code: "IFRS S1",
    title: "General Sustainability-related Financial Disclosures",
    category: "G",
    theme: "可持续发展相关财务披露",
    requirementSummary: "披露可持续发展相关风险和机遇对企业前景、商业模式和财务表现的影响。",
    requiredEvidenceTypes: ["公司治理", "合规与风控", "财务/业务数据"],
    suggestedMetrics: ["重大风险机遇清单", "财务影响说明", "治理监督频次"],
    suggestedDepartments: ["董事会办公室", "财务部", "ESG办公室"],
    riskLevelIfMissing: "高",
  },
  {
    id: "issb-governance",
    standardId: "issb-lite",
    code: "IFRS S1-GOV",
    title: "Governance",
    category: "G",
    theme: "治理",
    requirementSummary: "披露董事会和管理层对可持续发展相关风险和机遇的监督与职责分工。",
    requiredEvidenceTypes: ["公司治理", "合规与风控"],
    suggestedMetrics: ["董事会审议次数", "管理层汇报频次", "ESG 绩效挂钩指标"],
    suggestedDepartments: ["董事会办公室", "ESG办公室"],
    riskLevelIfMissing: "高",
  },
  {
    id: "issb-strategy",
    standardId: "issb-lite",
    code: "IFRS S1-STR",
    title: "Strategy",
    category: "G",
    theme: "战略",
    requirementSummary: "披露相关风险和机遇对战略、商业模式、价值链和财务规划的影响。",
    requiredEvidenceTypes: ["公司概况", "财务/业务数据", "合规与风控"],
    suggestedMetrics: ["重大风险机遇数量", "受影响业务线", "战略响应项目数量"],
    suggestedDepartments: ["战略发展部", "财务部"],
    riskLevelIfMissing: "高",
  },
  {
    id: "issb-risk-management",
    standardId: "issb-lite",
    code: "IFRS S1-RM",
    title: "Risk Management",
    category: "G",
    theme: "风险管理",
    requirementSummary: "披露识别、评估、优先排序和监控可持续发展相关风险的流程。",
    requiredEvidenceTypes: ["合规与风控", "公司治理"],
    suggestedMetrics: ["风险评估覆盖率", "重大风险数量", "整改完成率"],
    suggestedDepartments: ["风控部", "审计部"],
    riskLevelIfMissing: "高",
  },
  {
    id: "issb-metrics-targets",
    standardId: "issb-lite",
    code: "IFRS S1-MT",
    title: "Metrics and Targets",
    category: "G",
    theme: "指标与目标",
    requirementSummary: "披露用于管理和监控重大风险机遇的指标、目标、进展和数据口径。",
    requiredEvidenceTypes: ["财务/业务数据", "环境数据", "员工与社会责任"],
    suggestedMetrics: ["关键 ESG 指标清单", "目标完成率", "数据边界说明"],
    suggestedDepartments: ["ESG办公室", "财务部"],
    riskLevelIfMissing: "中",
  },
  {
    id: "issb-ifrs-s2-climate",
    standardId: "issb-lite",
    code: "IFRS S2",
    title: "Climate-related Disclosures",
    category: "E",
    theme: "气候披露",
    requirementSummary: "披露气候相关治理、战略、风险管理、指标和目标的整体情况。",
    requiredEvidenceTypes: ["环境数据", "合规与风控", "财务/业务数据"],
    suggestedMetrics: ["气候风险清单", "温室气体排放量", "气候目标完成率"],
    suggestedDepartments: ["ESG办公室", "环境管理部", "财务部"],
    riskLevelIfMissing: "高",
  },
  {
    id: "issb-climate-risks-opportunities",
    standardId: "issb-lite",
    code: "IFRS S2-RO",
    title: "Climate-related Risks and Opportunities",
    category: "E",
    theme: "气候风险机遇",
    requirementSummary: "披露气候相关物理风险、转型风险和机遇及其对业务和财务的影响。",
    requiredEvidenceTypes: ["环境数据", "合规与风控", "财务/业务数据"],
    suggestedMetrics: ["物理风险清单", "转型风险清单", "气候机遇项目数量"],
    suggestedDepartments: ["ESG办公室", "战略发展部", "财务部"],
    riskLevelIfMissing: "高",
  },
  {
    id: "issb-ghg-emissions",
    standardId: "issb-lite",
    code: "IFRS S2-GHG",
    title: "Scope 1, Scope 2, Scope 3 GHG Emissions",
    category: "E",
    theme: "温室气体排放",
    requirementSummary: "披露范围一、范围二和范围三温室气体排放及核算边界、方法和数据来源。",
    requiredEvidenceTypes: ["环境数据", "财务/业务数据"],
    suggestedMetrics: ["范围一排放", "范围二排放", "范围三排放", "排放强度"],
    suggestedDepartments: ["环境管理部", "ESG办公室"],
    riskLevelIfMissing: "高",
  },
  {
    id: "issb-transition-plan",
    standardId: "issb-lite",
    code: "IFRS S2-TP",
    title: "Climate Transition Plan",
    category: "E",
    theme: "气候转型计划",
    requirementSummary: "披露气候转型目标、行动计划、资源投入和进展跟踪。",
    requiredEvidenceTypes: ["环境数据", "公司概况", "财务/业务数据"],
    suggestedMetrics: ["转型项目投入", "减排目标进度", "低碳技术项目数量"],
    suggestedDepartments: ["战略发展部", "ESG办公室", "财务部"],
    riskLevelIfMissing: "高",
  },
  {
    id: "issb-scenario-analysis",
    standardId: "issb-lite",
    code: "IFRS S2-SA",
    title: "Scenario Analysis",
    category: "E",
    theme: "情景分析",
    requirementSummary: "披露气候情景分析方法、关键假设、韧性评估和结果应用。",
    requiredEvidenceTypes: ["合规与风控", "财务/业务数据", "公司概况"],
    suggestedMetrics: ["情景数量", "关键假设清单", "韧性评估结论"],
    suggestedDepartments: ["战略发展部", "风控部", "财务部"],
    riskLevelIfMissing: "高",
  },
];
